local extensions = {
  'autopairs',
  'bullets',
  'catppucchin',
  'cmp',
  'comment_nvim',
  'dap',
  'dbui',
  'dired',
  'drag_visuals',
  'emmet_vim',
  'fidget',
  'filetype',
  'gh',
  'gitsigns',
  'go',
  'hydra',
  'indent_blankline',
  'lazygit',
  'lightspeed',
  'lsp_colors',
  'lsputils',
  'lualine',
  'luasnip',
  'neotest',
  'null_ls',
  'nvim_gps',
  'nvim_tree',
  'orgmode',
  'refactoring',
  'spellsitter',
  'swift',
  'telescope',
  'terminal',
  'todo_comments',
  'treesitter',
  'trouble',
  'vim_markdown',
  'vimtex',
  'which_key',
  'workspaces',
  'yabs',
}

for _, extension in ipairs(extensions) do
  require("extensions." .. extension)
end
