Opts = {
  autoindent     = true,
  background     = "dark",
  backspace      = "eol,start,indent",
  backup         = false,
  cmdheight      = 1,
  cursorline     = true,
  expandtab      = true,
  fileencoding   = "utf-8",
  foldcolumn     = "1",
  foldenable     = true,
  foldexpr       = "nvim_treesitter#foldexpr()",
  foldlevelstart = 10,
  foldmethod     = "expr",
  grepprg        = "rg --vimgrep --smart-case --no-heading",
  guifont        = "FiraCode Nerd Font",
  hlsearch       = true,
  ignorecase     = true,
  incsearch      = true,
  indent_size    = 2,
  laststatus     = 3,
  lazyredraw     = true,
  list           = true,
  listchars      = "tab:\u{BB}\u{BB},trail:\u{B7},nbsp:~",
  magic          = true,
  matchtime      = 2,
  modeline       = true,
  mouse          = "a",
  number         = true,
  numberwidth    = 5,
  relativenumber = true,
  ruler          = true,
  scrolloff      = 7,
  shell          = '/bin/zsh',
  shiftround     = true,
  showcmd        = true,
  showmatch      = true,
  showmode       = false,
  smartcase      = true,
  smartindent    = false,
  smarttab       = true,
  spell          = true,
  spelllang      = "en_us",
  splitbelow     = true,
  splitright     = true,
  swapfile       = false,
  syntax         = "on",
  tags           = "./tags;",
  termguicolors  = true,
  textwidth      = 80,
  timeoutlen     = 500,
  undofile       = true,
  updatetime     = 300,
  wildignore     = "*.o,*~,*.pyc,*/.git/*,*.hg/*,*/.svn/*,*/.DS_Store",
  wildmenu       = true,
  wildmode       = "longest,list:full",
  winbar         = "%n%=%m %t",
  wrap           = true,
  writebackup    = false,
}

Theming = {
  colorscheme = "catppuccin",
}

LSP = {
  enabled        = true,
  highlight_word = true,
  virtual_text   = true,
  servers = {
    primary = {
      "angularls",
      "bashls",
      "clangd",
      "cssls",
      "dockerls",
      "erlangls",
      "graphql",
      "html",
      "jdtls",
      "jedi_language_server",
      "prismals",
      "rls",
      "rust_analyzer",
      "solargraph",
      "sourcekit",
      "stylelint_lsp",
      "texlab",
      "tsserver",
      "vimls",
      "volar",
      "yamlls",
    },
    regular = {
      "ccls",
      "pylsp",
      "terraformls",
      "terraform_lsp",
    },
    custom = {
      "denols",
      "elixirls",
      "emmet_ls",
      "gopls",
      "java_language_server",
      "jsonls",
      "sqlls",
      "sumneko_lua",
      "tailwindcss",
      "vuels",
    },
  },
}

Completion = {
  enabled = true,
  autopairs = true,
  items = 10,
  completeopt = "menuone,noselect",
}

Treesitter = {
  enabled = true,
  rainbow = true,
  parsers = {
    "bash",
    "c",
    "cpp",
    "css",
    "dockerfile",
    "elixir",
    "go",
    "graphql",
    "html",
    "http",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "latex",
    "lua",
    "org",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "toml",
    "typescript",
    "tsx",
    "vim",
    "vue",
    "yaml",
  }
}

Debuggers = {
  "python",
  "ccppr_vsc",
  "lua",
  "chrome",
  "jsnode",
}
