local config = {}

config.Opts = {
  autoindent     = true,
  background     = "dark",
  backspace      = "eol,start,indent",
  backup         = false,
  cmdheight      = 1,
  cursorline     = true,
  expandtab      = true,
  fileencoding   = "utf-8",
  foldcolumn     = "2",
  foldenable     = true,
  foldexpr       = "nvim_treesitter#foldexpr()",
  foldlevelstart = 10,
  foldmethod     = "expr",
  grepprg        = "rg --vimgrep --smart-case --no-heading",
  guifont        = "FiraCode Nerd Font",
  hlsearch       = true,
  ignorecase     = true,
  incsearch      = true,
  indent_size    = 2,
  laststatus     = 3,
  lazyredraw     = true,
  list           = true,
  listchars      = "tab:\u{BB}\u{BB},trail:\u{B7},nbsp:~",
  magic          = true,
  matchtime      = 2,
  modeline       = true,
  mouse          = "a",
  number         = false,
  numberwidth    = 5,
  relativenumber = false,
  ruler          = true,
  scrolloff      = 7,
  shell          = '/bin/zsh',
  shiftround     = true,
  showcmd        = true,
  showmatch      = true,
  showmode       = false,
  smartcase      = true,
  smartindent    = false,
  smarttab       = true,
  spell          = true,
  spelllang      = "en_us",
  splitbelow     = true,
  splitright     = true,
  swapfile       = false,
  syntax         = "on",
  tags           = "./tags;",
  termguicolors  = true,
  textwidth      = 80,
  timeoutlen     = 500,
  undofile       = true,
  updatetime     = 300,
  wildignore     = "*.o,*~,*.pyc,*/.git/*,*.hg/*,*/.svn/*,*/.DS_Store",
  wildmenu       = true,
  wildmode       = "longest,list:full",
  wrap           = true,
  writebackup    = false,
}

config.Theming = {
  colorscheme = "catppuccin",
}

config.LSP = {
  enabled        = true,
  highlight_word = true,
  virtual_text   = true,
  servers = {
    primary = {
      "angularls",
      "bashls",
      "clangd",
      "cssls",
      "dockerls",
      "erlangls",
      "graphql",
      "html",
      "jdtls",
      "jedi_language_server",
      "prismals",
      "rls",
      "rust_analyzer",
      "solargraph",
      "sourcekit",
      "stylelint_lsp",
      "texlab",
      "tsserver",
      "vimls",
      "volar",
    },
    regular = {
      "ccls",
      "pylsp",
      "terraformls",
      "terraform_lsp",
    },
    custom = {
      "deno",
      "elixir",
      "go",
      "java",
      "jsonls",
      "sql",
      "vue",
      "yaml",
    },
  },
}

config.Completion = {
  enabled = true,
  autopairs = true,
  items = 10,
  completeopt = "menuone,noselect",
}

config.Treesitter = {
  enabled = true,
  rainbow = true,
  parsers = {
    "bash",
    "c",
    "cpp",
    "css",
    "dockerfile",
    "elixir",
    "go",
    "graphql",
    "html",
    "http",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "latex",
    "lua",
    "org",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "toml",
    "typescript",
    "tsx",
    "vim",
    "vue",
    "yaml",
  }
}

-- Plugins that need extra configuration
-- These names need to align with one of the files/directories in the
-- lua/extensions directory
config.Extensions = {
  'autopairs',
  'bullets',
  'catppucchin',
  'cmp',
  'comment_nvim',
  'dap',
  'dbui',
  'diffview',
  'drag_visuals',
  'emmet_vim',
  'fidget',
  'filetype',
  'gitsigns',
  'go',
  'indent_blankline',
  'lab',
  'lazygit',
  'lightspeed',
  'lsp_colors',
  'lsputils',
  'lualine',
  'luasnip',
  'neotest',
  'null_ls',
  'nvim_gps',
  'nvim_tree',
  'orgmode',
  'refactoring',
  'spellsitter',
  'surround',
  'swift',
  'telescope',
  'terminal',
  'todo_comments',
  'treesitter',
  'trouble',
  'vim_markdown',
  'vimtex',
  'which_key',
  'workspaces',
  'yabs',
}

return config
