local telescope = require 'telescope.builtin'
local telescope_extensions = require('telescope').extensions

return {
  { "<leader>f",  group = "Telescope stuff" },
  { "<leader>f'", telescope.resume,                                                        desc = "Resume" },
  { "<leader>f;", telescope.command_history,                                               desc = "Command history" },
  { "<leader>f?", telescope.search_history,                                                desc = "Search history" },
  { "<leader>fB", require('extensions.telescope.custom.java').build_files,                 desc = "Java Build Files" },
  { "<leader>fD", telescope.lsp_definitions,                                               desc = "LSP Definitions" },
  { "<leader>fG", telescope.git_status,                                                    desc = "Git" },
  { "<leader>fI", telescope.lsp_implementations,                                           desc = "LSP Implementations" },
  { "<leader>fJ", require('extensions.telescope.custom.java').files,                       desc = "Java Files" },
  { "<leader>fL", telescope_extensions.luasnip.luasnip,                                    desc = "Luasnip" },
  { "<leader>fO", telescope.oldfiles,                                                      desc = "Old files (recent)" },
  { "<leader>fP", require('utils.core').search_nvim,                                       desc = "Private config" },
  { "<leader>fR", telescope.registers,                                                     desc = "Registers" },
  { "<leader>fS", "<cmd>lua require('telescope.builtin').lsp_document_symbols()<cr><C-u>", desc = "Symbols" },
  { "<leader>fT", telescope.treesitter,                                                    desc = "Treesitter" },
  { "<leader>fb", telescope.buffers,                                                       desc = "Buffers" },
  { "<leader>fc", telescope.commands,                                                      desc = "Commands" },
  { "<leader>fd", function() telescope.diagnostics({ bufnr = 0 }) end,                     desc = "Local diagnostics" },
  { "<leader>fe", telescope.resume,                                                        desc = "Resume" },
  { "<leader>ff", telescope.find_files,                                                    desc = "Files" },
  { "<leader>fg", telescope_extensions.live_grep_args.live_grep_args,                      desc = "Live grep" },
  { "<leader>fh", telescope.help_tags,                                                     desc = "Help tags" },
  { "<leader>fi", telescope.lsp_implementations,                                           desc = "LSP Implementations" },
  { "<leader>fj", telescope.jumplist,                                                      desc = "Jumplist" },
  { "<leader>fk", telescope.keymaps,                                                       desc = "Keymaps" },
  { "<leader>fm", telescope.marks,                                                         desc = "Marks" },
  { "<leader>fn", telescope.diagnostics,                                                   desc = "Global diagnostics" },
  { "<leader>fo", telescope.quickfixhistory,                                               desc = "Quickfix History" },
  { "<leader>fp", telescope.pickers,                                                       desc = "Pickers" },
  { "<leader>fq", telescope.quickfix,                                                      desc = "Quickfix" },
  { "<leader>fr", telescope.lsp_references,                                                desc = "LSP References" },
  { "<leader>ft", telescope.grep_string,                                                   desc = "This word" },
  { "<leader>fz", telescope.tags,                                                          desc = "Tags" },

  { "<leader>fl",  group = "LSP Stuff" },
  { "<leader>fld", telescope.diagnostics,          desc = "Diagnostics" },
  { "<leader>fls", telescope.lsp_document_symbols, desc = "LSP Document Symbols" },

  { "<leader>fs",  "<cmd>w<cr>", desc = "Save file" },
}
