return {
  { "<leader>n", group = "Org-Roam" },
  { "<leader>nc",  desc = "Org-Roam Capture" },
  { "<leader>nf",  desc = "Org-Roam Find or Create" },
  { "<leader>naa", desc = "Add alias" },
  { "<leader>noa", desc = "Add orign" },
  { "<leader>n.",  desc = "Completes node under cursor" },
  { "<leader>nn",  desc = "Next node" },
  { "<leader>np",  desc = "Prev node" },
  { "<leader>ni",  desc = "Insert node" },
  { "<leader>nm",  desc = "Insert node immediate" },
  { "<leader>nq",  desc = "Open backlinks in QF" },
  { "<leader>nar", desc = "Remove alias" },
  { "<leader>nor", desc = "Remove the origin" },
  { "<leader>nl",  desc = "Toggle org-roam node-view" },
  { "<leader>nb",  desc = "Toggle fixed org-roam node-view" },

  { "<leader>nd", group = "Org-Roam Dailies" },
  { "<leader>ndD", desc = "Capture a specific date's note" },
  { "<leader>ndN", desc = "Capture today's note" },
  { "<leader>ndT", desc = "Capture tomorrow's note" },
  { "<leader>ndY", desc = "Capture yesterday's note" },
  { "<leader>nd.", desc = "Navigate to dailies note directory" },
  { "<leader>ndf", desc = "Navigate to next note" },
  { "<leader>ndb", desc = "Navigate to prev note" },
  { "<leader>ndn", desc = "Go to today" },
  { "<leader>ndt", desc = "Go to tomorrow" },
  { "<leader>ndy", desc = "Go to yesterday" },
}
