return {
  { "<leader>o$", desc = "Org: Archive subtree" },
  { "<leader>o'", desc = "Org: Edit special" },
  { "<leader>o,", desc = "Org: Change priority" },
  { "<leader>oA", desc = "Org: Archive current headline" },
  { "<leader>oJ", desc = "Org: Move subtree down" },
  { "<leader>oK", desc = "Org: Move subtree up" },
  { "<leader>oe", desc = "Org: Export" },

  { "<leader>oi",  group = "Insert" },
  { "<leader>oi!", desc = "Timestamp Inactive" },
  { "<leader>oi.", desc = "Timestamp" },
  { "<leader>oiT", desc = "TODO Heading" },
  { "<leader>oid", desc = "Deadline" },
  { "<leader>oih", desc = "Heading" },
  { "<leader>ois", desc = "Schedule" },
  { "<leader>ok",  desc = "Org SRC: Abort changes" },
  { "<leader>oo",  desc = "Org: Open at point" },
  { "<leader>or",  desc = "Org: Refile" },
  { "<leader>ot",  desc = "Org: Set tags on current headline" },
  { "<leader>ow",  desc = "Org SRC: Write changes" },
  { "<leader>ox",  group = "Clock" },
  { "<leader>oxe", desc = "Org: Set Effort" },
  { "<leader>oxi", desc = "Org: Clock in" },
  { "<leader>oxj", desc = "Org: Clock GoTo" },
  { "<leader>oxo", desc = "Org: Clock out" },
  { "<leader>oxq", desc = "Org: Cancel Clock" },
}
