require 'plugins.autopairs'
require 'plugins.catppucchino'
require 'plugins.cmp'
require 'plugins.comment_nvim'
require 'plugins.drag_visuals'
require 'plugins.emmet_vim'
require 'plugins.filetype'
require 'plugins.fzf'
require 'plugins.gitsigns'
require 'plugins.nvim_gps'
require 'plugins.gutentags'
require 'plugins.indent_blankline'
require 'plugins.instant_markdown'
require 'plugins.lsputils'
require 'plugins.lsp_colors'
require 'plugins.lualine'
require 'plugins.luasnip'
require 'plugins.mappings'
require 'plugins.mdeval'
require 'plugins.neoterm'
-- require 'plugins.nerdtree'
require 'plugins.null_ls'
require 'plugins.nvim_tree'
-- require 'plugins.octo'
require 'plugins.orgmode'
require 'plugins.project_nvim'
require 'plugins.package_info'
-- require 'plugins.snap'
require 'plugins.refactoring'
require 'plugins.rest_nvim'
-- require 'plugins.sneak_vim'
require 'plugins.telescope'
require 'plugins.terminal'
-- require 'plugins.test'
require 'plugins.todo_comments'
require 'plugins.treesitter'
require 'plugins.trouble'
require 'plugins.vim_markdown'
require 'plugins.vim_smoothie'
require 'plugins.vimtex'
require 'plugins.which_key'
require 'plugins.zen_mode'
