require("vim._core.ui2").enable({
  enable = true,
  msg = {
    targets = {
      [""] = "msg",
      empty = "cmd",
      bufwrite = "msg",
      confirm = "cmd",
      emsg = "msg",
      echo = "msg",
      echomsg = "msg",
      echoerr = "msg",
      completion = "cmd",
      list_cmd = "pager",
      lua_error = "msg",
      lua_print = "msg",
      progress = "pager",
      rpc_error = "msg",
      quickfix = "msg",
      search_cmd = "cmd",
      search_count = "cmd",
      shell_cmd = "pager",
      shell_err = "msg",
      shell_out = "pager",
      shell_ret = "msg",
      undo = "msg",
      verbose = "msg",
      wildlist = "cmd",
      wmsg = "msg",
      typed_cmd = "cmd",
    },
    cmd = {
      height = 0.5,
    },
    dialog = {
      height = 0.5,
    },
    msg = {
      height = 0.3,
      timeout = 5000,
    },
    pager = {
      height = 0.5,
    },
  },
})
